README.md

Focus on how to make this logic reliable and observable while also require very little code to implement.

Add detailes about Segment sending logic.

---

README.md

Updated the README file to include details about our current shell-script based architecture.

Update README with current architecture

---

cmd/querygen/main.go
go.mod
querygen/querygen.go
querygen/querygen_test.go

It took a while to figure out where to put things.
This is not 100% done, I've no idea yet how to build and run things from the CLI, without `cd`ing all over the place, but at least the VSCode Go plugin can use this layout nicely.

Sekelton Go files

---

querygen/querygen.go
querygen/querygen_test.go

Only Application create events are desired at this time.

chore(RHTAPWATCH-173): Remove unecessary Application events

---

querygen/userjourney_fs.go
querygen/userjourney_fs_test.go
scripts/get-workspace-map.sh
scripts/splunk-to-segment.sh

Include the UserAgent field in all events sent to Segment

feat(RHTAPWATCH-387): Include the UserAgent field

---

kwok/Dockerfile
kwok/getuidmap.go
kwok/getuidmap_test.go
kwok/kwok_container_template.yml
kwok/user-signups.sh

1. Reworked scripts from #20.
2. created sample test to test get-uid-map.sh returned output.
3. Modified kwok/user-signups.sh to patch complaintUsername to usersignup yaml.
How to test:
1. First build the image using `podman build --build-arg CLUSTER_NAME=tester -t kwok -f kwok/Dockerfile .`
2. Now run the go test

test(RHTAPWATCH-382): test get-uid-map.sh

---

deploy/map-maker-role.yaml
deploy/map-maker-rolebinding.yaml
deploy/map-maker-sa.yaml
deploy/uid-map-maker-job.yaml
deploy/ws-map-maker-job.yaml
scripts/uid-map-maker-job.sh
scripts/ws-map-maker-job.sh

The jobs syncs data from the RHTAP clusters to config maps.
All scripts and resources tested manually on the preprod cluster.

feat(RHTAPWATCH-473): Jobs for user and WS maps

---

cmd/querygen/main.go
querygen/querygen.go
querygen/querygen_test.go
querygen/userjourney_fs.go

Produce a segment event when a build PipelineRun succeeds or fails.

chore(RHTAPWATCH-151): build PipelineRun success and failure events

---

querygen/querygen.go
querygen/userjourney_fs.go

Add repository data fields to build pipeline events reported to Segment.
Tested by running the new code locally and inspecting query results.

feat(RHTAPWATCH-511): Report repository data

---

Dockerfile

Make our main image match the requirements of the Red Hat Enterprise Policy so that it can be released via RHTAP.

chore(RHTAPWATCH-132): Fit to RH policy

---

cmd/querygen/main.go
querygen/querygen.go
querygen/ujquery.go

Add tracking of component creation, update and deletion events.

feat(RHTAPWATCH-533): component segment events

---

.github/workflows/precommit.yaml
.pre-commit-config.yaml

Adds a step to the pre-commit github workflow to run gitlint check on every opened pull request's commit message.
[RHTAPWATCH-177](https://issues.redhat.com/browse/RHTAPWATCH-177)
Running pre-commit and gitlint manually.

chore(RHTAPWATCH-177): run gitlint check for opened PR

---

README.md

Update the arch drawing in README

---

querygen/querygen.go
querygen/ujquery.go

Make sure all events reported to Segment include an "application" field so that we can use it as a "group value" to group events.

feat(RHTAPWATCH-547) Application fields everywhere

---

.github/workflows/pull_request_and_push.yaml
.pre-commit-config.yaml
go.mod

add go-mod-tidy check to the repository

chore(RHTAPWATCH-150): add go-mod-tidy

---

.pre-commit-config.yaml
querygen/k8s_audit_fieldset.go
querygen/k8s_audit_fieldset_test.go
querygen/querygen.go
querygen/ujquery.go
querygen/ujquery_test.go
queryprint/queryprint.go
queryprint/queryprint_test.go
scripts/runner_test.go
segment/uploader_test.go
stats/series_test.go
webfixture/webfixture.go
webfixture/webfixture_test.go

add go source checks for the repo

chore(RHTAPWATCH-150): go source checks

---

.github/workflows/unit_tests.yaml

Adds a code coverage report on each opened pull request.
A token was implemented in the repo for it to work.
depends on [RHTAPWATCH-208](https://issues.redhat.com/browse/RHTAPWATCH-208)  ( #109 )
[RHTAPWATCH-134](https://issues.redhat.com/browse/RHTAPWATCH-134)
not tested yet.

chore(RHTAPWTCH-134): run codecov on each opened PR

---

CONTRIBUTING.md
kwok/Dockerfile
kwok/inittab
kwok/kwok_container_default.yml

Changed the dockerfile so that multiple clusters are created.
Changed the inittab file so that all clusters are started and are proxied.
Changed the kwok yaml file to expose api ports for all clusters.
Please describe the tests that you ran to verify your changes. Provide
instructions so we can reproduce. Please also list any relevant details
for your test configuration

chore(RHTAPWATCH-479): add member clusters to kwok

---

CONTRIBUTING.md
kwok/kubeconfig

Add kubeconfig file for using the kwok-provided clusters.
Please describe the tests that you ran to verify your changes. Provide
instructions so we can reproduce. Please also list any relevant details
for your test configuration

chore(RHTAPWATCH-479): add kwok kubeconfig file

---

containerfixture/containerfixture.go

A change made a while ago to the container fixture removed by mistake the line running the test function itself, resulting in the test cases not running, yet returning a positive response.
This change fix that.
Ran all the tests with failed data to see they are failing as expected, then fixed them and verified the result changed as well.

fix: containerized test are working

---

CONTRIBUTING.md

Please describe the tests that you ran to verify your changes. Provide
instructions so we can reproduce. Please also list any relevant details
for your test configuration

doc: submodule doc change

---

.snyk
.tekton/segment-bridge-pull-request.yaml
.tekton/segment-bridge-push.yaml
fetch-uj-records/fetch-uj-records_test.go
splunk-to-segment/splunk-to-segment_test.go

RHTAPWATCH-160
- Add SAST check
Output:

chore(RHTAPWATCH-160): Run SAST checks for each opened PR

---

.gitlint

Please describe the tests that you ran to verify your changes. Provide
instructions so we can reproduce. Please also list any relevant details
for your test configuration

chore: add new bot name to gitlint

---

.tekton/segment-bridge-pull-request.yaml
.tekton/segment-bridge-push.yaml

add rpm-signature-scan task to pipelines

chore(KFLUXVNGD-83): add rpm-signature-scan task to pipelines
