redhat-appstudio/segment-bridge

scripts/fetch-uj-records.sh, scripts/get-uid-map.sh, scripts/splunk-to-segment.sh
A set of shell scripts for:
- Fetching RHTAP UserJounrney events from Splunk
- Cross-referencing usernmaes in events with UserSignup resources to map from cluster username for SSO user IDs
- Formatting the events into Segment event records suitable for uploading via the bulk send API.
=> Fetch user journey events from Splunk

README.md
Adds a guide on how to deploy a containerized Splunk instance. 
This will be a part of a future testing platform for Splunk.
=> chore(RHTAPWATCH-283): instructions for deploying Splunk instance

scripts/mk-segment-batch-payload.sh, scripts/segment-mass-uploader.sh, scripts/segment-uploader.sh, scripts/splunk-to-segment.sh
Created tooling to send data into Segment.
For testing purposes the funcitonality was split into three scripts:
- `mk-segment-batch-payload.sh` - For creating JSON records for the Segment batch API
- `segment-uploader.sh` - For actually talking to the batch API
- `segment-mass-uploader.sh` - For splitting a stream of records into right-sized chunks for uploading and then repeatedly calling `segment-uploader.sh`
Also needed a slight change to `splunk-to-segment.sh` to make it emit compact records instead of formatted data.
=> Complete the process of sending data to Segment

scripts/fetch-uj-records.sh
We found out that sometimes we get two resource create events in the audit log, both of which are accepted by the API server but only one of which is actually creating the resource record.
To tell which is the actual creation record we need to ensure we have a `resourceVersion` field in the `respobseObject` we get back from the creation action.
=> fix(RHTAPWATCH-355): Remove false creation events

cmd/querygen/main.go, querygen/querygen.go, querygen/querygen_test.go, scripts/fetch-uj-records.sh
Create the `querygen` Go program for generating query strings for Splunk
and use that in `fetch-uj-records.sh` instead of the bash code we had
for this before.
Doing this as a first step to switching to having multiple queryes and
more complex ones. Using Go for this allows for more complex query
generating logic then wnat we can easily do in `bash`.
This PR depends on #12
=> refactor(RHTAPWATCH-116): `querygen` Go program

scripts/fetch-uj-records.sh
fetch-uj-records script queries Splunk via curl, add retry option to enable retries on transient failures.
Jira: RHTAPWATCH-321
=> chore(RHTAPWATCH-321): Add retry option to Splunk query calls

README.md
The order of commands portrayed on the README file included trying to access the cluster before completing the setup.
This change reorders the commands so it works on a fresh install.
=> chore: modify order of commands for running kwok

webfixture/webfixture.go, webfixture/webfixture_test.go
Adding a little test function that would be useful for testing things that make simple calls into web servers, and do not care too much about the response. The main candidate for sing this is
`segment-mass-uploader.sh`.
=> test(RHTAPWATCH-311): Mini HTTP test framework

cmd/querygen/main.go, go.mod, go.sum, querygen/querygen.go, querygen/querygen_test.go, queryprint/queryprint.go, queryprint/queryprint_test.go, scripts/fetch-uj-records.sh
Add support in `querygen` for generating and printing multiple queries as well as support in `fetch-uj-records.sh` run running them.
In the process also add one additional query for querying PipelineRuns
=> feat(RHTAPWATCH-374): Run multiple Splunk queries

scripts/get-workspace-map.sh
For each cluster, the script searches for namespaces with label toolchain.dev.openshift.com/type set to tenant and maps the namespace name to the value of label toolchain.dev.openshift.com/space.
=> feat(RHTAPWATCH-371): add script mapping namespace to workspace

kwok/Dockerfile, kwok/entrypoint.sh, kwok/toolchain.dev.openshift.com_usersignups.yaml, kwok/user-signups.sh
Jira: [RHTAPWATCH-323](https://issues.redhat.com/browse/RHTAPWATCH-323) 
Use base image to create kwok cluster and usersignup script to create usersignups
cmd to test this :
`podman build --build-arg CLUSTER_NAME=tester -t custom-image .`
`podman run --rm -it -p 8080:8080 custom-image`
=> feat(RHTAPWATCH-323): add usersignup to kwok cluster

scripts/splunk-to-segment.sh
When event_verb returned from Splunk query not present in the event_verb_map, pass original value instead of null
=> chore(RHTAPWATCH-373): Support query-originated event verbs

scripts/splunk-to-segment.sh
Some resources don't have a userId field. This change introduces a fallback mechanism to lookup the SSO UID for the workspace owner in such cases.
=> feat(RHTAPWATCH-372): Map resource namespaces to SSO UIDs

Dockerfile
- Build Go binaries in the first stage
- Copy them from builder in second stage
=> chore(RHTAPWATCH-375): Support Go binaries in our job container image

Dockerfile
The main image build was failing when running in OpenShift and Podman because it was being done in a root-owned directory.
=> fix: image build failing in OpenShift & Podman

cmd/querygen/main.go, querygen/querygen.go, querygen/querygen_test.go, querygen/userjourney_fs.go, querygen/userjourney_fs_test.go, scripts/fetch-uj-records.sh, scripts/splunk-to-segment.sh
A `PipelineRun` started event is detected by searching for update events on the `status` subresource where the `Succeeded` condition has a reason of `Running` with 0 tasks complete.
=> RHTAPWATCH-154: Produce a segment event when a build PipelineRun starts

scripts/get-uid-map.sh
When running get-uid-map.sh script there are some uid's without value. Updated the script to filter out those usernames.
Jira Url: https://issues.redhat.com/browse/RHTAPWATCH-302
Ran the script locally to check the desired output
=> chore(RHTAPWATCH-302): Update get-uid-map.sh to filter no usernames

cmd/querygen/main.go, querygen/querygen.go, querygen/querygen_test.go, querygen/userjourney_fs.go
Produce a segment event when the clair-scan task completes
Task:
[RHTAPWATCH-95](https://issues.redhat.com/browse/RHTAPWATCH-95)
=> chore(RHTAPWATCH-95): Produce a segment event when the clair-scan task completes

splunk/Dockerfile, splunk/scripts/pre-run.sh
In the Splunk's dockerfile, the Splunk DB is being moved to `/opt/splunk/splunk` so it'll be to allow copying it during build time to the second stage of the build.
This change place the Splunk DB in a dedicated directory under /var/ so that it won't be confused for a Splunk binary directory
[RHTAPWATCH-481](https://issues.redhat.com/browse/RHTAPWATCH-481)
Manual tests building and running the image with podman, 
entering the container to check that everything in place,
as well as running the unit tests that use the Splunk image.
=> chore(RHTAPWATCH-481): move Splunk's image buildtime database

kwok/Dockerfile, kwok/kwok_container_template.yml
Building the `kwok` image via `podman kube play` was failing because the image Dockerfile was assuming the build context directory is the repo root instead of the `kwok/` directory where the file resides.
=> fix(RHTAPWATCH-507): failing to build kwok image

splunk/splunk_container_default.yaml
Adds a pre-filled version of `splunk_container_template` with default details to allow easily running the pod manually with `podman kube build`
https://github.com/redhat-appstudio/segment-bridge/pull/41#discussion_r1321900272
manually tested with `podman kube build`
=> chore: pre-filled Splunk container definition

splunk/Dockerfile
Splunk communicate on port 8000 and 8089, yet the Dockerfile pointed at 8080 as an exposed port, instead of 8000.
=> chore: corrected exposed port for Splunk

cmd/querygen/main.go, querygen/querygen.go, querygen/querygen_test.go, querygen/userjourney_fs.go
Produce a segment event when a Release succeeds or fails.
- Ensure that Release resource events are Sent to Segment
- Ensure that the resource success/failure state changes are reflected to Segment.
[RHTAPWATCH-183](https://issues.redhat.com/browse/RHTAPWATCH-183)
Tested the query locally in Splunk.
=> chore(RHTAPWATCH-183): Produce a segment event when a Release succeeds or fails.

CONTRIBUTING.md
Updates the contribution guide with the following:
- how to login to quay in order to pull images from it.
- setting `kwok` build as optional, explaining how to pull the image instead.
- modify the kwok build command so it'll work from the root of the repo.
- adds information regarding usage of .netrc file under Splunk.
- fixed some code-blocks indentations.
RHTAPWATCH-498
Docs change, no tests.
=> docs(RHTAPWATCH-498): updated quay, kwok, and netrc information

kwok/kwok_container_default.yml
Adds a pre-filled version of `kwok_container_template` with default details to allow easily running the pod manually with `podman kube build`
=> chore: pre-filled Kwok container definition

Dockerfile
The one we used seems to be blacklisted in some way, also switch to the UBI based image so we can get it from the free registry.
=> Update Go Toolset image

querygen/querygen.go, querygen/ujquery.go
Producing a segment event whenever a build PipelineRun is originated from a PR, which means it was triggered by a webhook or by a change to a PR.
=> chore(RHTAPWATCH-386): events for PR originated build PipelineRuns

querygen/querygen.go, querygen/ujquery.go
Forward Component "patch" event to Segment while also extracting a more elaborate event verb where possible, since some patch events can be mapped directly to UI actions.
=> feat(RHAPWATCH-535): Component patch events

querygen/querygen.go
We have the Build PipelineRun and Release events that can end successfully or with failure. So far we have had separate event names for the different completion statuses. This made analysis in Amplitude more difficult. This PR unifies the event names.
=> Unify run event names

.pre-commit-config.yaml, scripts/fetch-uj-records.sh, scripts/segment-mass-uploader.sh, scripts/segment-uploader.sh, splunk/scripts/pre-run.sh
Adds a step to the pre-commit github workflow to run shellcheck linter
on every opened pull request.
[RHTAPWATCH-509](https://issues.redhat.com/browse/RHTAPWATCH-509)
Running `pre-commit run --all-files` as well as the script's tests after formatting.
=> chore(RHTAPWATCH-509): run shellcheck for opened PR

querygen/k8s_audit_fieldset.go, querygen/k8s_audit_fieldset_test.go, querygen/querygen.go, querygen/ujquery.go, querygen/ujquery_test.go
Introduce a new K8sAuditFieldSet object built on top of our exiting FieldSet object, but specialized for queries against the audit log. A key feature is the ability to specify different field settings for different K8s resource types. This will make it easier to have common output fields that require different ways to calculate them for different resources.
As part of the work here, introduced the new object type and re-factored UserJourneyQuery to use it.
=> refator(RHTAPWATCH-547): Per-K8s API field sets

.github/dependabot.yml
Adds a Dependabot to github actions in order to automate dependency updates.
Dependabot will update the following:
- docker (all 3 dockerfiles in the repository)
- gomod (go)
- pip (python)
- github actions
[RHTAPWATCH-200](https://issues.redhat.com/browse/RHTAPWATCH-200)
YAML file was linted, cannot test locally besides in another repo.
=> chore(RHTAPWATCH-200): automate dependency updates

.github/dependabot.yml, OWNERS
Seems like dependabot's configuration file does
not accept aliases. In order to avoid repeating the reviewers list multiple times across the file,
added a reviewers section under the OWNERS file instead.
=> fix: dependabot configurations

.github/workflows/precommit.yaml
This change makes it so instead running the pre-commit action only when a PR is created, it'll run when it is created, re-opened, or when it has any changes (new commits, push events, rebases)
=> chore: pre-commit running for the whole review process

.github/workflows/pull_request.yaml, .gitlint, requirements.lock, requirements.txt
Fix an issue where the pre-commit github action that runs gitlint skipped linting the commit message.
This was done by installing an additional pre-commit gitlint hook that is designed for ci specifically.
Running the pre-commit hook locally
=> chore(RHTAPWATCH-177): run gitlint on CI

.github/workflows/gitlint.yaml, .github/workflows/pull_request_and_push.yaml
Separates gitlint from the workflow for pull-request and push, as it cannot and should not run on push.
The new workflow runs it only for the pull-request process itself.
=> fix: gitlint workflow runs on pull request only

.gitlint
gitlint now ignores commits made by dependabot and red-hat-trusted-app-pipeline as those are usually
invalid (either have long lines or do not sign off commits)
Ignored my own user and committed invalid commits, seeing they are skipped by gitlint.
=> chore: gitlint ignores bot users

kwok/kwok_container_template.tmpl, splunk/splunk_container_template.tmpl
The recent linting of the repository left an error on `splunk_container_template`, leaving the pod's
"name" invalid and therefor it is not being filled as part of the template. this fix it.
None
Run the container before & after the fix, using podman and using the go tests.
=> fix: lint issues with splunk container template

.github/dependabot.yml
yamllint produce a warning on each and every PR
regarding a missing "---" at the beginning of
`dependabot.yml`. this change should rid us of the warning.
=> chore: fix yamllint warning on dependabot

.github/pull_request_template.md
Removes the "Description" title from the pull request template.
The idea beyond this change is that we are to expect description to be a part of the commit message anyway, meaning it'll be automatically added to the beginning of the pull request description anyway.
having the description title there just adds the need to manually move the text, which don't seem to happen much, creating confusing PR description.
None
Not needed
=> chore: remove description title from PR

splunk/scripts/log_indexing.sh
We encountered an edge-case in which the curl command that initiate the log indexing for Splunk silently fail. As the looping check we have later on only checks for indexing that already started, therefore ignoring what failed to begin.
This change will fail the script on the initiation of the log indexing, given an error will occur.
None
Manual test:
```
[1/2] STEP 10/10: RUN bash -o errexit /opt/splunk/pre-run.sh
Indexing logs...
Indexing /opt/splunk/test_logs/log_example.log
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: 
Encountered an error while initiating indexing for …
```
=> chore: error-handling for log indexing

.github/workflows/unit_tests.yaml
Adds a new GH actions workflow that runs the GO unit tests on each opened pull request.
This excludes the kwok and splunk packages tests, as those include deployment of containers, which we don't want the GH actions container to deal with.
This is also made into a new PR-only workflow to allow for the future addition of codecov.
[RHTAPWATCH-208](https://issues.redhat.com/browse/RHTAPWATCH-208)
Running the unit tests locally with the command used in the workflow.
=> chore(RHTAPWATCH-208): Run GO unit tests for each opened PR

.github/workflows/gitlint.yaml, chore-scripts/check-same-go-toolset.sh
Add a job that ensure we use the same Go Toolset image when building our production image and when running tests in CI.
=> Add job for checking the Go Toolset image

kwok/Dockerfile, kwok/entrypoint.sh, kwok/inittab
Make our kwok image use the busybox version of sys-v init to launch and monitor processes. This will allow us to make it run multiple processes.
=> refactor(RHTAPWATCH-479): kwok image use sysv-init

Dockerfile
The version we were using contains security vulnerabilities
=> chore: Update ose-tools image

.github/workflows/gitlint.yaml, .gitlint
We need to do this because using `pip` with the default Python in the Ubuntu image does not work any more.
=> chore: Install Python for GitLint action
